### ISSUE TITLE
导出的课表中没有地点 是否为bug?

### ISSUE THREAD

**Issue by Icy-Cat** [weearc/cqu_timetable_new#20]
如题

**Comment by Hagb** [comment]
是用 json 还是 xlsx 生成的？
能用记事本打开生成的课表，截一页发上来不？

**Comment by Hagb** [comment]
确实是 bug。尝试使用最新版？

**Comment by Icy-Cat** [comment]
> 确实是 bug。刚刚更新了，尝试使用最新版？

还是无法显示地点

**Comment by Hagb** [comment]
> > 确实是 bug。刚刚更新了，尝试使用最新版？
> 
> 还是无法显示地点

能用记事本打开生成的课表，截一页发上来不？

方便的话最好能够再提供生成课表用的 json 或 xlsx

**Comment by Icy-Cat** [comment]
> > > 确实是 bug。刚刚更新了，尝试使用最新版？
> > 
> > 
> > 还是无法显示地点
> 
> 能用记事本打开生成的课表，截一页发上来不？
> 
> 方便的话最好能够再提供生成课表用的 json 或 xlsx

![Snipaste_2021-08-31_08-55-24](https://user-images.githubusercontent.com/78187357/131424516-dbe88f32-fbb7-4d71-9d3a-ddf9ab8d8ce0.jpg)
![Snipaste_2021-08-31_08-57-24](https://user-images.githubusercontent.com/78187357/131424611-e97ab233-6b65-4aa2-833b-9122da453b3f.jpg)

**Comment by Hagb** [comment]
我这里无法复现。请确认是否重新下载并使用了 GitHub 上的最新版。
![图片](https://user-images.githubusercontent.com/10961094/131445734-9f12a838-50e0-4745-8748-8a69ac626514.png)

**Comment by weearc** [comment]
@Icy-Cat 请使用如下方法安装最新版本：
```bash
pip install cqu-timetable-new
```
如果先前使用的是预编译windows binary请尝试直接使用 pip 安装后的版本。

**Comment by Icy-Cat** [comment]
已pip安装最新版本 版本为cqu-timetable-new 0.3.2.14.1
运行后导出的ics文件中仍然无法获取地点信息 config文件如下图

![Snipaste_2021-08-31_20-42-22](https://user-images.githubusercontent.com/78187357/131504834-bf0faef8-3f0f-4b26-ba15-b9558928faa0.jpg)

**Comment by weearc** [comment]
@Icy-Cat 请尝试更新至 `0.3.2.143`，该版本已经通过 CI 传至 pypi.org ，链接地址：https://pypi.org/project/cqu-timetable-new/0.3.2.143/

**Comment by Icy-Cat** [comment]
> @Icy-Cat 请尝试更新至 `0.3.2.143`，该版本已经通过 CI 传至 pypi.org ，链接地址：[pypi.org/project/cqu-timetable-new/0.3.2.143](https://pypi.org/project/cqu-timetable-new/0.3.2.143/)
[已解决]
感谢 更新至最新版本后已解决地点不实现的问题 同时能否问一下 为什么从github中git出的版本无法解决问题 而pip安装的版本可以

**Comment by weearc** [comment]
> > @Icy-Cat 请尝试更新至 `0.3.2.143`，该版本已经通过 CI 传至 pypi.org ，链接地址：[pypi.org/project/cqu-timetable-new/0.3.2.143](https://pypi.org/project/cqu-timetable-new/0.3.2.143/)
> 
> [已解决]
> 感谢 更新至最新版本后已解决地点不实现的问题 同时能否问一下 为什么从github中git出的版本无法解决问题 而pip安装的版本可以

通常使用 pip 对本地 package 进行配置使用在版本号想同时不会进行更新，需要手动移除 wheel 并重新设置
